channels:
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - nodefaults
dependencies:
  - gcc=10.4.0
  - gxx=10.4.0
  - cuda=12.1
  - python=3.9.18
  - pip=23.2.1
  - pdm=2.11.1
  - apoorvkh::auto-dotenv=1.0
platforms:
  - linux-64
